import { App } from "global.slint";
import { Button, HorizontalBox, Palette, Slider, VerticalBox } from "std-widgets.slint";

export { App }

export component AppWindow inherits Window {
    title: App.name;

    in property<image> image <=> image.source;
    in property<length> image-height: 100px;
    in property<length> image-width: 500px;

    property<[color]> brush-colors: [
        Colors.black,
        Colors.gray,
        Colors.white,
        Colors.lightpink,
        Colors.crimson,
        Colors.orange,
        Colors.gold,
        Colors.greenyellow,
        Colors.forestgreen,
        Colors.turquoise,
        Colors.cornflowerblue,
        Colors.midnightblue,
        Colors.indigo,
        Colors.darkorchid,
    ];
    property<color> brush-color: brush-colors[0];
    property<float> brush-width: 3.0;

    pure callback clear();
    pure callback draw-end(int, int);
    pure callback draw-start(int, int);
    pure callback draw(int, int, color, float);

    VerticalBox {
        Text {
            text: App.name;
        }

        Text {
            text: "Version: \{App.version}";
        }

        HorizontalBox {
            padding: 0;

            for brush-color in root.brush-colors: Rectangle {
                background: brush-color;
                border-color: root.brush-color == brush-color ? Palette.accent-background : Palette.border;
                border-radius: 2px;
                border-width: 2px;
                height: self.width;

                touch:= TouchArea {
                    clicked => { root.brush-color = parent.background; }
                }
            }
        }

        HorizontalBox {
            padding: 0;

            Text {
                text: "Brush Width: \{Math.round(root.brush-width)}";
            }

            brush-width-slider:= Slider {
                maximum: 10.0;
                minimum: 1.0;
                value: root.brush-width;

                changed(value) => { root.brush-width = self.value }
            }
        }

        Button {
            text: "Clear";
            clicked => {
                root.clear();
            }
        }

        Rectangle {
            background: Palette.control-background;
            border-color: Palette.border;
            border-radius: 2px;
            border-width: 2px;
            height: root.image-height + self.border-width * 2;
            width: root.image-width + self.border-width * 2;

            image:= Image {
                height: root.image-height;
                image-fit: fill;
                width: root.image-width;
                x: parent.border-width;
                y: parent.border-width;
            }

            touch_area:= TouchArea {
                mouse-cursor: crosshair;
                moved => {
                    root.draw(touch_area.mouse-x / 1px, touch_area.mouse-y / 1px, root.brush-color, root.brush-width);
                }
                pointer-event(event) => {
                    if (event.button == PointerEventButton.left) {
                        if (event.kind == PointerEventKind.down) {
                            root.draw-start(touch_area.mouse-x / 1px, touch_area.mouse-y / 1px);
                        } else if (event.kind == PointerEventKind.up) {
                            root.draw-end(touch_area.mouse-x / 1px, touch_area.mouse-y / 1px);
                        }
                    }
                }
            }
        }
    }
}