import { App } from "global.slint";
import { Button, Palette, VerticalBox } from "std-widgets.slint";

export { App }

export component AppWindow inherits Window {
    title: App.name;

    in property<image> image <=> image.source;
    in property<length> image-height: 100px;
    in property<length> image-width: 500px;

    pure callback clear();
    pure callback draw-end(int, int);
    pure callback draw-start(int, int);
    pure callback draw(int, int);

    VerticalBox {
        Text {
            text: App.name;
        }

        Text {
            text: "Version: \{App.version}";
        }

        Button {
            text: "Clear";
            clicked => {
                root.clear();
            }
        }

        Rectangle {
            background: Palette.control-background;
            border-color: Palette.border;
            border-radius: 2px;
            border-width: 2px;
            height: root.image-height + self.border-width * 2;
            width: root.image-width + self.border-width * 2;

            image:= Image {
                height: root.image-height;
                image-fit: fill;
                width: root.image-width;
                x: parent.border-width;
                y: parent.border-width;
            }

            touch_area:= TouchArea {
                mouse-cursor: crosshair;
                moved => {
                    root.draw(touch_area.mouse-x / 1px, touch_area.mouse-y / 1px);
                }
                pointer-event(event) => {
                    if (event.button == PointerEventButton.left) {
                        if (event.kind == PointerEventKind.down) {
                            root.draw-start(touch_area.mouse-x / 1px, touch_area.mouse-y / 1px);
                        } else if (event.kind == PointerEventKind.up) {
                            root.draw-end(touch_area.mouse-x / 1px, touch_area.mouse-y / 1px);
                        }
                    }
                }
            }
        }
    }
}